## numpy : Numerical Python

- 벡터(1차원 배열)나 매트릭스(2차원, 3차원 등)  n차 다 차원 배열(ndarray : n dimentional array)을 사용하면 리스트보다 계산 속도가 빠르다.
- 리스트와 달리 각 항목은 모두 같은 타입의 숫자(정수 or 소수 등)이어야 함
    - 1 차원 축 행( axis = 0) : Vector
    - 2 차원 축 열( axis = 1) : Matrix(행열)
    - 3 차원 축 채널 ( axis = 2) : Tensor(3차원 이상)
- list와 배열 np.array(list) 비교

# *(꼽) 의미

### ☞ list  : 반복(복사) 출력
### ☞ 배열 : np.array(list) : 직접 항목에 적용  ->리스트 형태로 [ ] 출력
### ☞ import

In [1]:
import numpy as np 

In [70]:
lst = [1,2,10]

# 3번 반복의 의미
print(lst * 3)

[1, 2, 10, 1, 2, 10, 1, 2, 10]


# 배열 : np.array()

In [3]:
import numpy as np

In [4]:
lst

[1, 2, 10]

In [71]:
arr = np.array(lst)
arr

array([ 1,  2, 10])

In [72]:
#항목에 직접 곱해짐
print(arr*3)

[ 3  6 30]


In [73]:
#일반 리스트와 , np.array()배열 자료를 꼭 구분해야함.
print(arr + 100)

[101 102 110]


### list 자료

In [74]:
#일반적인 list 
x=[1,2,3]
y=[4,5,6]

print(x+y)

[1, 2, 3, 4, 5, 6]


### list 자료 -> np 배열 자료 변환 : np.array()

In [10]:
x=[1,2,3]
y=[4,5,6]

ax=np.array(x)
ay=np.array(y)

print(x+y)
print(ax+ay) # 원소단위 직접 계산

[1, 2, 3, 4, 5, 6]
[5 7 9]


# 2차원 배열

In [11]:
# 리스트 안에 리스트가 있는 것 - 2차원배열
data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

print(data)
type(data)  # list

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


list

In [12]:
arr2 = np.array(data)

print(arr2)
type(arr2) # numpy.ndarray

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


numpy.ndarray

In [13]:
#data type 
arr2.dtype

dtype('int64')

In [15]:
#원소 갯수
arr2.size

12

In [16]:
#행열의 구조를 보여줌 
arr2.shape

(4, 3)

- 배열의 특정 위치를 인덱싱하여 구함 

In [18]:
# 배열의 특정 위치를 인덱싱하여 구함
# -> 위치값 : [행 인덱스번호,열 인덱스번호] <- 행 : 인덱스번호+1 , 열 : 인덱스번호 +1 =>(두 번째 행,세 번째 열) 
arr2[1,2]

6

In [19]:
arr2[1][2]

6

In [20]:
arr2[2,1]

8

In [21]:
arr2[0]

array([1, 2, 3])

In [22]:
arr2[2]

array([7, 8, 9])

In [24]:
arr2[1,2],arr2[2][1]

(6, 8)

### 슬라이스(slice) - [ ], [ : ], [ : : ], [ , ]
- 행의 일부 또는 열의 일부를 구하는 방법
- [ 행 인덱스 , 열 인덱스] -> [ : , : ] [시작:n-1행 인덱스 , 시작 : n-1열 인덱스 ]

# 자격증 시험 슬라이스 나옴ㅇㅇ 

In [25]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
arr2[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [29]:
arr2[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
#제일 마지막행
arr2[-1]

array([10, 11, 12])

In [32]:
arr2[-2]

array([7, 8, 9])

In [34]:
#-2 + -1 해야하니까 -3 0 -1 -2 열 뽑기 .
arr2[:,:-2]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [36]:
# -2,-3
arr2[:-1,:-2]

array([[1],
       [4],
       [7]])

# arange
- range : 파이썬에서 기본적으로 숫자를 생성, 혹은 위치 값 출력
- arange : numpy라이브러리, 배열에서 일정한 숫자를 생성, 혹은 위치 값 출력

In [66]:
# 0 ~ 11까지 숫자 생성
data0= range(12)  # -> (0,12,1)
print(data0)

range(0, 12)


In [69]:
#del list 위에 list라는 변수를 만들어서 사용했기때문에 del 삭제해줄 필요가 있음
x = list(range(12))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [54]:
import numpy as np

In [56]:
data1=np.arange(12)
data1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
data2 = data1.reshape(4,3)
data2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# np.arange(12).reshapre(4,3)
- arange와 reshape의 각각 생성된 자료를 취합해서 한번에 생성

In [77]:
data= np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

- 슬라이스 예제

In [78]:
x= data[:,:-1]
print(x)

[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]


In [79]:
xx=data[:,:-2]
print(xx)

[[0]
 [3]
 [6]
 [9]]


In [81]:
y=data[:,-1] # 뒤에는 ~ 부터 n-1까지 슬라이싱. 없으면 고유 번호로 할 것.
print(y)

[ 2  5  8 11]


In [82]:
z=data[-1,-1]
print(z)

11


In [84]:
data= np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
#이런 문제도 나온디야
data[data<4]=0
data

array([[ 0,  0,  0],
       [ 0,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
data<4

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [89]:
data[data<5]=0
data

array([[ 0,  0,  0],
       [ 0,  0,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
data<=4

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [91]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
data= np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
data.mean()

5.5

In [95]:
data.mean(axis=0) # axis=0 열 기준 평균 산출

array([4.5, 5.5, 6.5])

In [96]:
data.mean(axis=1) # axis=1 행 기준 

array([ 1.,  4.,  7., 10.])

In [98]:
data.mean(0) # axis 생략 가능 

array([4.5, 5.5, 6.5])

In [99]:
data.mean(1)

array([ 1.,  4.,  7., 10.])

In [100]:
data.sum()

66

In [102]:
data.sum(0) #열기준

array([18, 22, 26])

In [103]:
data.sum(1) # 행기준

array([ 3, 12, 21, 30])